name: Test Dev Builds

on:
  pull_request:
    branches: main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch run +py=${{ matrix.python-version }} test:run
